{{- include "adp-helm-library.container-secret" (list . "backstage-demo-1.container-secret") -}}
{{- define "backstage-demo-1.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
