{{- include "adp-helm-library.deployment" (list . "backstage-demo-1.deployment") -}}
{{- define "backstage-demo-1.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "backstage-demo-1.container") }}
{{- end -}}
