environment: development
environmentCode:
name: backstage-demo-1
namespace: fcp-grants
workstream: fcp-grants
image: backstage-demo-1

labels:
  component: web

appInsights:
  connectionString:

containerConfigMap:
  name: backstage-demo-1-config-map

containerSecret:
  name: backstage-demo-1-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
